services:
  db:
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=root
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=clinical-db
